Repository josh-velasquez/Twijj, pull requests merged in 2020-04, with the labels that each got.

#29 Create profile
  client/src/actions/index.js
  client/src/actions/types.js
  client/src/components/GoogleAuth.js
  client/src/components/profile/Profile.js
  client/src/components/profile/ProfileModal.js
  client/src/reducers/authReducer.js
  client/src/reducers/profileReducer.js
Labels: enhancement

#26 #17: Layout of Stream Viewing Page
  .gitignore
  client/src/actions/index.js
  client/src/components/App.js
  client/src/components/SideNav.js
  client/src/components/streams/StreamChat.js
  client/src/components/streams/StreamShow.js
  client/src/components/style.css
  rtmpserver/package-lock.json
Labels: enhancement, ready for review

#45 Fixed bug where duplicate streams are created when creating new stream
  client/src/actions/index.js
  client/src/reducers/streamReducer.js
Labels: bug

#44 #9: Chat
  client/package-lock.json
  client/package.json
  client/src/actions/index.js
  client/src/actions/types.js
  client/src/components/streams/StreamChat.js
  client/src/components/streams/StreamShow.js
  client/src/components/style.css
  client/src/reducers/chatReducer.js
  client/src/reducers/index.js
Labels: ready for review

#47 Home page tiles
  client/src/assets/thumbnails.json
  client/src/components/streams/StreamList.js
Labels: ready for review

#53 35: Viewer count
  client/src/actions/index.js
  client/src/components/streams/StreamShow.js
  client/src/reducers/chatReducer.js
Labels: enhancement, ready to merge

#55 50: Client Side to Enable Firebase Rules
  client/src/actions/index.js
  client/src/components/GoogleAuth.js
  client/src/components/Header.js
  client/src/components/streams/StreamList.js
Labels: ready for review

#64 Remove the existing warns/errors in console.
  client/src/actions/index.js
  client/src/components/Header.js
  client/src/components/SideNav.js
  client/src/components/profile/ProfileModal.js
  client/src/components/streams/StreamShow.js
Labels: bug, ready for review

#63 61: Handle socket disconnects from chat.
  client/src/actions/index.js
  client/src/actions/types.js
  client/src/reducers/chatReducer.js
Labels: ready for review

#69 65: Fix Firefox Crashing When Viewing Inactive Stream
  client/src/components/streams/StreamShow.js
Labels: bug, ready for review

#70 Added some margin between items in streamlist.
  client/src/components/streams/StreamList.js
Labels: enhancement
